In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
%matplotlib widget
from matplotlib.widgets import Slider

In [2]:
df = pd.read_csv("./data/handwritten.csv")

In [3]:
data = np.array(df)

In [4]:
data.shape

(42000, 785)

In [8]:
y = data[:,0]
x = data[:,1:]

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train = x_train/255.0
y_train = tf.keras.utils.to_categorical(y_train, num_classes= 10)

In [26]:
model = Sequential([
        Dense(128, activation = 'relu', input_shape=(784,),name = 'L1'), 
        Dense(64, activation = 'relu', name = 'L2'),
        Dense(10, activation = 'softmax', name = 'L3'),
], name = "HandWritten")

model.compile(
    loss = 'categorical_crossentropy',
    optimizer = tf.keras.optimizers.Adam(0.001),
    metrics = ['accuracy'])

In [27]:
model.summary()

Model: "HandWritten"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 L1 (Dense)                  (None, 128)               100480    
                                                                 
 L2 (Dense)                  (None, 64)                8256      
                                                                 
 L3 (Dense)                  (None, 10)                650       
                                                                 
Total params: 109,386
Trainable params: 109,386
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.fit(x_train,y_train, epochs = 10,batch_size=32)

Epoch 1/10
985/985 [==============================] - 3s 3ms/step - loss: 0.0209 - accuracy: 0.9928
Epoch 2/10
985/985 [==============================] - 3s 3ms/step - loss: 0.0150 - accuracy: 0.9945
Epoch 3/10
985/985 [==============================] - 2s 2ms/step - loss: 0.0157 - accuracy: 0.9950
Epoch 4/10
985/985 [==============================] - 2s 2ms/step - loss: 0.0113 - accuracy: 0.9959
Epoch 5/10
985/985 [==============================] - 2s 2ms/step - loss: 0.0092 - accuracy: 0.9970
Epoch 6/10
985/985 [==============================] - 2s 2ms/step - loss: 0.0152 - accuracy: 0.9949
Epoch 7/10
985/985 [==============================] - 3s 3ms/step - loss: 0.0137 - accuracy: 0.9951
Epoch 8/10
985/985 [==============================] - 2s 3ms/step - loss: 0.0109 - accuracy: 0.9962
Epoch 9/10
985/985 [==============================] - 2s 2ms/step - loss: 0.0075 - accuracy: 0.9975
Epoch 10/10
985/985 [==============================] - 2s 2ms/step - loss: 0.0127 - accuracy: 0.9963

In [30]:
predicted = model.predict(x_test)

329/329 [==============================] - 1s 1ms/step


In [44]:
sm_predicted = tf.nn.softmax(predicted).numpy()
print(f"two example output vectors:\n {sm_predicted[:2]}")
print("largest value", np.max(sm_predicted), "smallest value", np.min(sm_predicted))

two example output vectors:
 [[0.08533674 0.08533674 0.08533674 0.08533674 0.23196931 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.08533674 0.08533674 0.08533674 0.08533674 0.23196931
  0.08533674 0.08533674 0.08533674 0.08533674]]
largest value 0.23196931 smallest value 0.085336745


In [45]:
for i in range(len(x_test)):
    print(f"{predicted[i]}, category: {np.argmax(predicted[i])}")

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 1. 0. 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0.000000e+00 0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00
 0.000000e+00 0.000000e+00 2.397928e-19 0.000000e+00 0.000000e+00], category: 2
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
 0.0000000e+00 1.0000000e+00 0.0000000e+00 4.9584757e-35 0.0000000e+00], category: 6
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], c

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.], category: 5
[0. 0. 0. 

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.], category: 9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.], category: 8
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.], category: 6
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.], category: 4
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.], category: 1
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.], category: 7
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.], category: 0
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.], category: 2
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.], category: 3
[0. 1. 0. 

In [53]:
result = np.zeros(len(x_test))
for i in range(len(y_test)):
    r = y_test[i] == np.argmax(predicted[i])
    result[i] = r

In [59]:
print(f"Accuracy of the model on Test is {sum(result)/len(result)}")

Accuracy of the model on Test is 0.9697142857142858
